### ISSUE TITLE
Need more examples!

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#11]
Hi,

I bought NatCorder, but am pretty confused by its API. I managed to make a simple video recorder work, which is awesome. But now I want to take just a simple photo shot, and I am lost. How can this be accomplished? There is a JPGRecorder, and I was assuming I can use it for that purpose, but how can I actually trigger it so it would take one single picture and give me a file link to it?!

For a package at that price level, I would have expected convenience methods that make recording videos, taking photos and recording audio as simple as possible. Having low level access is awesome, but often times you won't need that.

At least, I would expect a lot of samples that show how to stitch everything together.

**Comment by olokobayusuf** [comment]
NatCorder is not built for capturing screenshots or photos, and we don't advertise it as doing so. [Unity already provides this functionality](https://docs.unity3d.com/ScriptReference/ScreenCapture.html).

**Comment by derwaldgeist** [comment]
Yep, but the Unity screenshot won't limit your shots to the input of a particular camera, i.e. it will always contain all UI elements as well. Why can't the JPGRecorder be used for that purpose? Seems as if it is just a question of how many frames you would record?

**Comment by derwaldgeist** [comment]
Also, I find the separation of NatCorder and NatDevice very confusing. Why not combine both packages into one? They are so much related to each other.

**Comment by derwaldgeist** [comment]
I tried it like this:

```cs
var recorder = new JPGRecorder(Screen.width, Screen.height);
var cameraInput = new CameraInput(recorder, clock, cameraManager.activeCamera);
await recorder.FinishWriting();
```

But this leads to an error:

```
MissingReferenceException: The object of type 'Texture2D' has been destroyed but you are still trying to access it.
```

**Comment by olokobayusuf** [comment]
> Why can't the JPGRecorder be used for that purpose?

It can, but it is not designed for this purpose. The `JPGRecorder` is designed for recording image sequences. I should stress this, **NatCorder is not designed to take screenshots**. You seem to have this misunderstanding.

> Seems as if it is just a question of how many frames you would record? In my case, 1 frame would be enough.

Using the `JPGRecorder` will be massively convoluted. You can simply render your target camera to a `RenderTexture`.

> Also, I find the separation of NatCorder and NatDevice very confusing. Why not combine both packages into one? They are so much related to each other.

NatDevice is a media device API, meaning using the camera and microphone; NatCorder is for recording video files. NatDevice's functionality is completely perpendicular to NatCorder's. Again I want to highlight your apparent misconception: NatCorder is not designed for single images/screenshots.

**Comment by olokobayusuf** [comment]
> I tried it like this:
> But this leads to an error:

Don't use NatCorder for this purpose. Render your game camera to a `RenderTexture`. The NatCorder approach amounts to using a bomb to lighting a candle; it *could* work, but there's a much (much) simpler way to achieve it. See [this question](https://gamedev.stackexchange.com/questions/173760/how-can-i-take-screenshots-with-two-cameras-simultaneously-in-unity) for pointers.

**Comment by derwaldgeist** [comment]
Ok, but how would I save this texture to a file, then?

**Comment by olokobayusuf** [comment]
> Ok, but how would I save this texture to a file, then?
> 
> Update: Found a way to do this:
> https://answers.unity.com/questions/1331297/how-to-save-a-texture2d-into-a-png.html
> 
> Will try it out.

Yup that's how you're supposed to do it. You can check out the `JPGRecorder` implementation for pointers (this recorder is implemented right there in C#).

**Comment by derwaldgeist** [comment]
Ok. Thanks. I hope this approach works in combination with AR. My actual use-case is to take a still image of the AR camera, but without any user-interface elements. Which already works perfectly using the MP4Recorder, so I thought I might use the JPGRecorder for the same purpose, but just for one image.

**Comment by olokobayusuf** [comment]
> Ok. Thanks. I hope this approach works in combination with AR. My actual use-case is to take a still image of the AR camera, but without any user-interface elements. Which already works perfectly using the MP4Recorder, so I thought I might use the JPGRecorder for the same purpose, but just for one image.

The `JPGRecorder` isn't what's responsible for only showing your game without UI; it is because of `CameraInput`. The `CameraInput` renders the camera(s) to a `RenderTexture` then fetches the raw pixel data to send to the recorder. This is also implemented in C# so you can look through it for pointers.
