### ISSUE TITLE
Crash on Samsung S10 when playing back video

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#15]
This is a followup to the closed #14.

I updated my S10 5G to the latest Android version today and then tried to record a video again on this device. Recording worked, but as soon as I played it back in the web view, the app totally went nuts. The screen went black first and then there were wild flashes. I had to kill the app completely.

When I restarted the app again and played the video back, it worked and I didn't see this flashing stuff again when recording new videos. Yet still, errors like these are just an unacceptable user experience. People might even think we broke their phone :-/ There are many inexperienced users out there who might perceive it like this.

I'm pretty sure that there's some issue in the encoded files (if you add an audio track), as was reported by `ffmpeg` and the Chromium guys. It's the third device now that shows strange behaviors. So I'd like to kindly ask to look into this again and try to resolve the encoding problems. Thanks.

**Comment by olokobayusuf** [comment]
It is generally the responsibility of the crashing app to not crash. There isn't anything NatCorder could possibly do to influence the behaviour of WebKit. You should file this bug with the Chromium folks, not here.

**Comment by derwaldgeist** [comment]
Well. I reported these problems to them, but they say it's a problem in the encoding of the video files.
