### ISSUE TITLE
Downsampling an audio file

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#16]
I am recording audio files using WAVRecorder, using Unity's microphone as an input. Since I want the output files as small as possible, I've set the sampling rate to 8khz or 12khz. The resulting WAV file resembles this sampling rate. However, the file size stays the same (10sec == 1.9 MB), but instead the duration of the audio clip increases (a 10sec recording gets stretched to 1 min). How can I prevent this? I would have expected WAVRecorder to down-sample the input accordingly.

**Comment by olokobayusuf** [comment]
The `WAVRecorder` does not resample audio; it writes the linear PCM as-is. To get 8KHz or 12KHz audio from Unity's `Microphone` API, you'll have to set Unity's DSP to use this sample rate in Audio Settings. The other option, which won't require overriding the audio configuration of your entire app, is to [use NatDevice](https://docs.natsuite.io/natcorder/integrations/natdevice#recording-the-microphone).

**Comment by olokobayusuf** [comment]
Just to clarify, NatCorder recorders are always created with their **input format**, for either video or audio. The only exceptions to this are the video bitrate and keyframe interval for `MP4Recorder` and `HEVCRecorder`; these specify compression settings on the output video stream in the MP4.
