### ISSUE TITLE
NatCorder crashes in iOS TestFlight version

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#17]
So far, the iOS version of my app worked fine. Thus, I pushed it to TestFlight to hand it over to our beta users.

Yet, the very first time I tried the video recording feature, the app crashed with an error related to writing the MP4 to disk. Here's the crash log:

[testflight_feedback.zip](https://github.com/natsuite/NatSuite-Examples/files/4964286/testflight_feedback.zip)

Interestingly, this only happens if you start the app for the very first time (after installing it from TestFlight). Subsequent runs work flawlessly. This was reproducible on the second install.

Any idea what's going on here?

**Comment by derwaldgeist** [comment]
This might be related to us asking for the permission to save the video to the album right after the write has finished. I will try to add an additional delay here and see if this changes something.

Wouldn’t explain why the crash actually happens, though, as I would expect that writing has finished completely if I had awaited the call.

**Comment by olokobayusuf** [comment]
Can you share your recording code? I have no clue what is going on. Running the first time vs. subsequent times should make absolutely no difference.

**Comment by derwaldgeist** [comment]
I tried to workaround this with some additional delays. I will try out and report back.

**Comment by olokobayusuf** [comment]
Anything on this? I'd like to close this issue.

**Comment by derwaldgeist** [comment]
Did some tests in the past days. Did not show up again, so I am closing this.
