### ISSUE TITLE
Video resolution/quality improvement

### ISSUE THREAD

**Issue by dhruvmodhapp** [natsuite/NatSuite-Examples#19]
Hello
I have an issue regarding video resolution/quality. I tried recording with 1080*1920. But recorded video looks blurry. This means quality of the video not look good.

I trying to record the camera view with Unity ARFoundation ar-camera.

**Does anybody have a solution for this?**

**Comment by olokobayusuf** [comment]
You can increase the [video bitrate when creating the recorder](https://docs.natsuite.io/natcorder/api/mp4recorder#creating-the-recorder).
