### ISSUE TITLE
Unity app showing that "App using microphone in background"

### ISSUE THREAD

**Issue by dhruvmodhapp** [natsuite/NatSuite-Examples#20]
I am using Natcorder and NatDevice for recording video and audio in my unity application. Bu has an issue with a notification that the android app using the **app is using a microphone in the background** 

How can we prevent to use a microphone app in the background? Because this is a serious privacy issue. Any help is appreciated @olokobayusuf 

![WhatsApp Image 2020-10-19 at 15 31 07](https://user-images.githubusercontent.com/46337334/96430978-8126f700-1220-11eb-850e-5087436d7ec5.jpeg)

**Comment by olokobayusuf** [comment]
You need to stop any running devices when your app goes into the background. I believe this issue only applies to the `AudioDevice` on Android. The `CameraDevice` already handles this, as do both devices on iOS.
