### ISSUE TITLE
Video not playing on Android (Unity) "no moov before mdat"

### ISSUE THREAD

**Issue by FectarDeveloper** [natsuite/NatSuite-Examples#23]
We've been using NatRecorder for recording video's so the user can share them (whatsapp etc).
But now we want to show those video's within the App with Unity.
iOS has no problems, but Android won't play the video's.

After much research and creating many different videos we found this error;
`mp4 error: no moov before mdat and the stream is not seekable`

We are using version 1.7.3 of NatRecorder.

Our code;

> // finish video recording
> _cameraInput?.Dispose();
> _audioInput?.Dispose();
> _audioDevice?.StopRunning();
> // finish writing
> var videoWriteTask = _mediaRecorder.FinishWriting();
> while (!videoWriteTask.IsCompleted && videoWriteTask.Exception == null)
> {
> 	yield return null;
> }

WORKING MP4 Example
https://spotoncms.blob.core.windows.net/0c90140a/bd872615_video.mp4

NOT LOADING MP4 Example 
https://spotoncms.blob.core.windows.net/0c90140a/75b0a37f_video.mp4

Both were made on the same devices, with the same recording settings.

**Comment by FectarDeveloper** [comment]
> 2021-03-03 13:16:33.251 2335-2417/io.spoton.viewer D/MPEG4Writer: PreAllocation disabled. fallocate : Operation not supported on transport endpoint, 95
> 2021-03-03 13:16:33.386 2335-9143/io.spoton.viewer D/MPEG4Writer: fpathconf _PC_FILESIZEBITS:64
> 2021-03-03 13:16:33.386 2335-9143/io.spoton.viewer D/MPEG4Writer: File size limit set to 4503599627370495 bytes implicitly
> 2021-03-03 13:16:33.386 2335-9143/io.spoton.viewer D/MPEG4Writer: MP4WtrCtrlHlpLooper Started
> 2021-03-03 13:16:33.386 2335-9143/io.spoton.viewer I/MPEG4Writer: limits: 4503599627370495/0 bytes/us, bit rate: -1 bps and the estimated moov size 3192 bytes
> 2021-03-03 13:16:33.386 2335-9154/io.spoton.viewer D/MPEG4Writer: kWhatNoIOErrorSoFar
> 2021-03-03 13:16:33.389 2335-9155/io.spoton.viewer I/MPEG4Writer: setStartTimestampUs: 0
> 2021-03-03 13:16:33.389 2335-9155/io.spoton.viewer I/MPEG4Writer: Earliest track starting time: 0
> 2021-03-03 13:16:33.518 2335-9156/io.spoton.viewer I/MPEG4Writer: setStartTimestampUs: 171163
> 2021-03-03 13:16:57.545 2335-9143/io.spoton.viewer D/MPEG4Writer: reset()
> 2021-03-03 13:16:57.545 2335-9143/io.spoton.viewer D/MPEG4Writer: Video track stopping. Stop source
> 2021-03-03 13:16:57.545 2335-9143/io.spoton.viewer D/MPEG4Writer: Video track source stopping
> 2021-03-03 13:16:57.545 2335-9143/io.spoton.viewer D/MPEG4Writer: Video track source stopped
> 2021-03-03 13:16:57.545 2335-9155/io.spoton.viewer I/MPEG4Writer: Received total/0-length (586/0) buffers and encoded 586 frames. - Video
> 2021-03-03 13:16:57.545 2335-9156/io.spoton.viewer I/MPEG4Writer: Received total/0-length (910/0) buffers and encoded 910 frames. - Audio
> 2021-03-03 13:16:57.545 2335-9143/io.spoton.viewer D/MPEG4Writer: Video track stopped. Status:0. Stop source
> 2021-03-03 13:16:57.546 2335-9156/io.spoton.viewer I/MPEG4Writer: Audio track drift time: 0 us
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer D/MPEG4Writer: Audio track stopping. Stop source
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer D/MPEG4Writer: Audio track source stopping
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer D/MPEG4Writer: Audio track source stopped
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer D/MPEG4Writer: Audio track stopped. Status:0. Stop source
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer D/MPEG4Writer: Duration from tracks range is [21297815, 21322445] us
> 2021-03-03 13:16:57.546 2335-9153/io.spoton.viewer D/MPEG4Writer: 0 chunks are written in the last batch
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer D/MPEG4Writer: WriterThread stopped. Status:0
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer I/MPEG4Writer: Adjust the moov start time from 0 us -> 0 us
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer I/MPEG4Writer: The mp4 file will not be streamable.
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer I/MPEG4Writer: MOOV atom was written to the file
> 2021-03-03 13:16:57.546 2335-9143/io.spoton.viewer D/MPEG4Writer: release()
> 2021-03-03 13:16:57.569 2335-9143/io.spoton.viewer D/MPEG4Writer: MP4WtrCtrlHlpLooper stopped
> 2021-03-03 13:16:57.569 2335-9143/io.spoton.viewer D/MPEG4Writer: Top 5 write durations(microseconds): #1:30 #2:31 #3:32 #4:34 #5:47
> 2021-03-03 13:16:57.570 2335-9143/io.spoton.viewer D/MPEG4Writer: reset()
> 2021-03-03 13:16:57.570 2335-9143/io.spoton.viewer D/MPEG4Writer: Video track stopping. Stop source
> 2021-03-03 13:16:57.570 2335-9143/io.spoton.viewer E/MPEG4Writer: Stop() called but track is not started or stopped
> 2021-03-03 13:16:57.570 2335-9143/io.spoton.viewer D/MPEG4Writer: Audio track stopping. Stop source
> 2021-03-03 13:16:57.570 2335-9143/io.spoton.viewer E/MPEG4Writer: Stop() called but track is not started or stopped
>

**Comment by olokobayusuf** [comment]
How are you playing back the video? Unity's `VideoPlayer` should be able to playback the video.

 Android's `MediaMuxer` will never create streamable MP4's. See [this answer on StackOverflow](https://stackoverflow.com/questions/24000026/mediamuxer-unable-to-make-mp4s-that-are-streamable).

**Comment by FectarDeveloper** [comment]
Unity VideoPlayer won't play these video's

**Comment by FectarDeveloper** [comment]
"The mp4 file will not be streamable."
Is only called on certain video's, those aren't playable with the Unity VideoPlayer.

**Comment by FectarDeveloper** [comment]
Here are the playback error's

> 2021-03-03 14:26:20.160 667-667/? E/SurfaceFlinger: Attempt to set frame rate on an unrecognized IGraphicBufferProducer
> 2021-03-03 14:26:20.727 17237-17997/io.spoton.viewer E/NuCachedSource2: source returned error -1010, 0 retries left
> 2021-03-03 14:26:20.727 1302-4598/? E/Utils: did not find mime type
> 2021-03-03 14:26:20.729 17237-17305/io.spoton.viewer W/Unity: AndroidVideoMedia: No tracks in https://spotoncms.blob.core.windows.net/0c90140a/c88b2163_video.mp4

**Comment by olokobayusuf** [comment]
> Here are the playback error's
> 
> > 2021-03-03 14:26:20.160 667-667/? E/SurfaceFlinger: Attempt to set frame rate on an unrecognized IGraphicBufferProducer
> > 2021-03-03 14:26:20.727 17237-17997/io.spoton.viewer E/NuCachedSource2: source returned error -1010, 0 retries left
> > 2021-03-03 14:26:20.727 1302-4598/? E/Utils: did not find mime type
> > 2021-03-03 14:26:20.729 17237-17305/io.spoton.viewer W/Unity: AndroidVideoMedia: No tracks in https://spotoncms.blob.core.windows.net/0c90140a/c88b2163_video.mp4

I think you're conflating unrelated issues. The file not being streamable has no effect on the issue at hand. All MP4's recorded with the native media API on Android **will not** be streamable. Try to playback a NatCorder-recorded video that is on the device, not on a remote server, and share the full logs in a `.txt` attachment.

**Comment by FectarDeveloper** [comment]
Ok. So downloaded video's are working! Thanks for the tip.
I (think i) understand why the video's will not be streamable.
What I don't understand is why some video's are streaming correctly on Android and ALL video's are streaming correctly on iOS.
which technicaly wouldn't be possible.

**Comment by olokobayusuf** [comment]
> Ok. So downloaded video's are working! Thanks for the tip.
> I (think i) understand why the video's will not be streamable.
> What I don't understand is why some video's are streaming correctly on Android and ALL video's are streaming correctly on iOS.
> which technicaly wouldn't be possible.

iOS works entirely differently, so I wouldn't compare behaviour across both platforms. I'm not sure why some videos stream on Android; I don't have enough information to really speculate. I'm closing this issue since you've verified that local videos work properly. You might want to inspect your server's response payloads.
