### ISSUE TITLE
Android: GifRecorder crashing if Scripting Backend is set to MONO

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#25]
Normally, I am using the IL2CPP Scripting backend for my AR Foundation app, since it is required under iOS. Unfortunately, IL2CPP doesn't report code lines in the logs (at least under Unity 2019.4), so I tried to switch the Backend to MONO for some debugging tasks under Android. The app itself worked fine, but it crashed once I used the GIF recorder.

[crash.txt](https://github.com/natsuite/NatSuite-Examples/files/6409403/crash.txt)

Any idea what's the reason for this?

**Comment by olokobayusuf** [comment]
Hey @derwaldgeist , so just to confirm, the `GIFRecorder` constructor crashes on Mono, but not IL2CPP? That's weird, and nothing comes to mind immediately. First, can you upgrade to NatCorder 1.8? Then try reproducing this, but capture the logs from app start to crash. I want to see if the native `GIFRecorder` constructor fails.

**Comment by derwaldgeist** [comment]
> just to confirm, the GIFRecorder constructor crashes on Mono, but not IL2CPP?

Yes, it crashes on Mono, but not IL2CPP. Since we need IL2CPP for Augmented Reality, we have no choice.

>  First, can you upgrade to NatCorder 1.8

I did, but Unity won't compile unless I enable the /unsafe flag now. Is this normal?

> Then try reproducing this, but capture the logs from app start

Ok, will do!

**Comment by olokobayusuf** [comment]
> Yes, it crashes on Mono, but not IL2CPP. Since we need IL2CPP for Augmented Reality, we have no choice.

The crash is coming from the JNI, which is much harder to figure out. If you're using IL2CPP to build, I guess you should be fine.

> I did, but Unity won't compile unless I enable the /unsafe flag now. Is this normal?

Can you share the compiler error? NatCorder has its own assembly definition which enables `/unsafe`, so you shouldn't need it in your main project.

**Comment by derwaldgeist** [comment]
> Can you share the compiler error?

Ah ok, it seems af this is only applied after a restart. I had the same problem when applying the /unsafe flag manually.

**Comment by olokobayusuf** [comment]
@derwaldgeist Sounds good. As for the stale files, I usually recommend deleting NatCorder in your project before importing an update.
