### ISSUE TITLE
iOS GIFRecorder: File size 3x higher than on Android

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#28]
If I record a GIF on iOS, the resulting file size is ~3x the size of the GIF on Android, using the same configuration. I am wondering why iOS blows the files up this much? In my setup, I am skipping 4 frames, and the frame duration is set to 0.15s. The width of the video is 100px in both cases. The resulting height is 216px on iOS and 200px on Android, due to the varying screen aspect ratios.

**Comment by olokobayusuf** [comment]
> If I record a GIF on iOS, the resulting file size is ~3x the size of the GIF on Android, using the same configuration. I am wondering why iOS blows the files up this much? In my setup, I am skipping 4 frames, and the frame duration is set to 0.15s. The width of the video is 100px in both cases. The resulting height is 216px on iOS and 200px on Android, due to the varying screen aspect ratios.

iOS uses a local color table (each frame gets its own color table) whereas Android uses a global color table (all frames share the same color table). On iOS, the LCT isn't configurable by NatCorder; it's the only way that the CoreGraphics framework renders GIF images.
