### ISSUE TITLE
NatDevice: Checking microphone permission without requesting it

### ISSUE THREAD

**Issue by derwaldgeist** [natsuite/NatSuite-Examples#30]
I bought NatDevice now and wanted to use its API for microphone permission detection. I found MediaDeviceQuery.RequestPermissions(), which works fine for actually requesting the permission. Is there also a way to only check it, without requesting it?

**Comment by olokobayusuf** [comment]
Hey @derwaldgeist , checking for permissions wasn't included. Here's the thought process behind that decision:

First, the semantics of `RequestPermissions` are that if the permission has been granted or denied by the user, then nothing happens, and the method simply returns that value as a `true` or `false`. So in this case, it degenerates to what you want--checking if the permission has been granted.

But if the request state is indeterminate--the user hasn't been asked yet--then the method shows the UI and once they decide, you get the value of their decision. Now switching over to the developer's perspective, we couldn't think of a good scenario where you'd want to know **if the permission state is indeterminate**, and this is the only information that an explicit permission check would give you over the current semantics. So we always 'force' the permission state to a known state (granted/denied) by asking for the permission, in which case `RequestPermissions` becomes a regular permissions check.

Let me know what you think, and if there's a scenario we haven't considered. All feedback is welcome 😉

**Comment by derwaldgeist** [comment]
Thanks for your extensive feedback. Let me rethink this.

In the meanwhile: I noticed that on Android, RequestPermissions() won't return at all if the permission has been denied. Shouldn't it return `false` instead?

**Comment by derwaldgeist** [comment]
So here's a use-case for HasPermissions before requesting them: On Android, there is an internal permissions state "deny and don't ask again'. If you cannot check for this state, you have to ask for the permissions all over again, i.e. at each app start. The problem is that this has unwanted side-effects. In my AR app, it makes the camera behave weirdly for a fraction of a second. All AR content gets into the front of the camera (as if it got stuck to it) and the camera gets dark for about half a second, at least if I use Unity's default PermissionRequest (yours did not work, see above). Since I don't have a way to tell if the user has definitely denied the request, I have to ask at least once per session (otherwise, the app could not react accordingly if the user enables the microphone manually, in the app's settings). So I have to live with that weird flash at least once per session.

**Comment by olokobayusuf** [comment]
> In the meanwhile: I noticed that on Android, `RequestPermissions()` won't return at all if the permission has been denied. It just silently fails. Shouldn't it return `false` instead? If I accept the permission, I get `true`. So my async code seems to be correct:

I just checked the code and you're right. The reason this happens is because on Android, NatDevice uses Unity's `Permissions` class [which doesn't have an indeterminate state](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/Android.Permission.html). So the NatDevice fix would mean that `RequestPermissions` always returns immediately, because Unity's API gives us no way of knowing if and when the dialog is displayed and dismissed.

> So here's a use-case for HasPermissions before requesting them: On Android, there is an internal permissions state "deny and don't ask again'. If you cannot check for this state, you have to ask for the permissions all over again, i.e. at each app start. Otherwise, the app could not react accordingly if the user enables the microphone manually, in the app's settings.

Permissions handling is another place where Android's terrible design shows. You can't request permissions from a standalone library. As such, NatDevice must rely on Unity.

**Comment by derwaldgeist** [comment]
I'm using Unity's version directly now, and it works with a combination of HasPermissions and RequestPermission. However, I ran into the problem I mentioned above (Unity forces me to ask for permissions at least once, causing side-effects). And yes, I agree, the whole permissions management in Unity is a pure mess. Totally inconsistent across devices and not working as documented. I was hoping that NatDevice would solve that for me :-)

**Comment by olokobayusuf** [comment]
Sounds good, I'm closing this issue.

**Comment by derwaldgeist** [comment]
Ok. Does that mean you won't fix it?

**Comment by olokobayusuf** [comment]
> Ok. Does that mean you won't fix it?

I've added a fix to NatDevice that will prevent the permission task from never completing on Android. Basically what i do is to request the permission, wait for 3 seconds (that should be enough time for the user to grant or reject), then return the value of `HasPermissions`.

**Comment by derwaldgeist** [comment]
That's exactly how I am doing it now. I'm using 1s though, seems to work reliably, since switching to the native dialog interrupts Unity anways.

**Comment by derwaldgeist** [comment]
Do you see any chance to enhance this to get the real Android permissions values, like the "don't ask me again" thing?

**Comment by olokobayusuf** [comment]
> Do you see any chance to enhance this to get the real Android permissions values, like the "don't ask me again" thing?

Not at all. The problem here is that Android itself has very poorly designed API's around something even as simple as permissions. A standalone service can't request permissions; only the `Activity` can, and in this case the activity is Unity. That's why we have to go through Unity.

**Comment by derwaldgeist** [comment]
Ok. Makes sense. I read something similar in an unsupported package from a Unity employee. So the only option would be that I roll it my own, as I have replaced the default Activity anyways.
